---
- name: Small Server
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Deploy servers
      clc_server:
        name: tday
        template: centos-7-64
        count: 1
        cpu: 1
        memory: 1
        group: Runner
        state: present
        add_public_ip: true
        public_ip_ports:
          - 22
          - 80
        ttl: 604800
      register: clc
    - name: debug
      debug: var=clc.server_ids

