---
- name: Thanksgiving Servers
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Deploy servers
      clc_server:
        name: tday
        template: ubuntu-14-64
        count: 2
        cpu: 1
        memory: 2
        group: Runner
        state: present
        ttl: 345600
      register: clc
    - name: debug
      debug: var=clc.server_ids
